name: CI with OpenID Connect

on:
  push:
    branches: [ main ]

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Prepare upload directory
        run: |
          mkdir upload
          rsync -av ./ upload/

      - name: Upload to Azure Storage via access key
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name "$ACCOUNT" \
              --account-key "$KEY" \
              --source "upload" \
              --destination '$web/noparsley' \
              --overwrite
        env:
          ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          KEY: ${{ secrets.AZURE_STORAGE_KEY }}